name: nakama-node-1
database:
  address:
    - "root_:pRvgcXZhcjwd9nG6DvTMilZv6xIoVRqb@dpg-d72osnu3jp1c7386n5ag-a:5432/nakama_a6dq"
logger:
  level: "DEBUG"
session:
  token_expiry_sec: 7200
runtime:
  js_entrypoint: "index.js"